# Generated by Django 5.1 on 2024-10-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode/'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='matricule',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='MATRICULE'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='NOM'),
        ),
    ]
