# Generated by Django 5.1 on 2024-09-07 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('motantpayer', models.IntegerField()),
                ('libelle', models.CharField(default='Frais', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('datepayement', models.DateField()),
                ('motantpayer', models.IntegerField()),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.eleve')),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frais.frais')),
            ],
        ),
    ]
