# Generated by Django 5.1 on 2024-09-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payement',
            name='numero',
        ),
        migrations.AddField(
            model_name='payement',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
