# Generated by Django 5.1 on 2024-10-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frais', '0002_remove_payement_numero_payement_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frais',
            options={'verbose_name_plural': 'Frais'},
        ),
        migrations.AlterField(
            model_name='frais',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='CODE'),
        ),
    ]
