# Generated by Django 5.1.1 on 2024-10-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frais', '0003_alter_frais_options_alter_frais_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payement',
            old_name='motantpayer',
            new_name='motantpaye',
        ),
        migrations.AddField(
            model_name='payement',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode/'),
        ),
    ]
